#![allow(clippy::invisible_characters)]

use liquid_core::Expression;
use liquid_core::FilterParameters;
use liquid_core::Result;
use liquid_core::Runtime;
use liquid_core::{Display_filter, Filter, FilterReflection, FromFilterParameters, ParseFilter};
use liquid_core::{Value, ValueView};

#[derive(Debug, FilterParameters)]
struct TimeZoneArgs {
    #[parameter(description = "Format ISO 8601 compliant datetime into a given timezone.", arg_type = "str")]
    tz_param: Option<Expression>,
}

#[derive(Clone, ParseFilter, FilterReflection)]
#[filter(
    name = "time_zone",
    description = "convert time to given timezone",
    parameters(TimeZoneArgs),
    parsed(TimeZoneFilter)
)]
pub struct TimeZone;

#[derive(Debug, FromFilterParameters, Display_filter)]
#[name = "time_zone"]
struct TimeZoneFilter {
    #[parameters]
    args: TimeZoneArgs,
}

impl Filter for TimeZoneFilter {
    fn evaluate(&self, input: &dyn ValueView, runtime: &dyn Runtime) -> Result<Value> {
        let args = self.args.evaluate(runtime)?;
        let input = input.to_kstr().to_string();

        let tz_str = args.tz_param.map(|x| x.to_string()).unwrap_or_default();
        if tz_str.is_empty() || input.is_empty() {
            return Ok(Value::scalar(input));
        }

        let normalized_tz = if let Some(val) = TIMEZONES.get(&tz_str.to_lowercase()) {
            *val
        } else if let Some(val) = PLACE_TIMEZONES.get(&tz_str) {
            *val
        } else {
            &tz_str
        };

        if let Ok(datetime) =  rb_date_parser::parse(&input) {
            if let Ok(tz) = normalized_tz.parse::<chrono_tz::Tz>() {
                let converted = datetime.with_timezone(&tz);
                let dt = liquid::model::DateTime::from_chrono_datetime(converted.fixed_offset());
                return Ok(Value::scalar(dt.to_string()));
            }
        }
        Ok(Value::scalar(input))
    }
}

use phf::phf_map;

static TIMEZONES: phf::Map<&'static str, &'static str> = phf_map! {
    "africa/abidjan"=>"Africa/Abidjan",
    "africa/accra"=>"Africa/Accra",
    "africa/addis_ababa"=>"Africa/Addis_Ababa",
    "africa/algiers"=>"Africa/Algiers",
    "africa/asmera"=>"Africa/Asmera",
    "africa/bamako"=>"Africa/Bamako",
    "africa/bangui"=>"Africa/Bangui",
    "africa/banjul"=>"Africa/Banjul",
    "africa/bissau"=>"Africa/Bissau",
    "africa/blantyre"=>"Africa/Blantyre",
    "africa/brazzaville"=>"Africa/Brazzaville",
    "africa/bujumbura"=>"Africa/Bujumbura",
    "africa/cairo"=>"Africa/Cairo",
    "africa/casablanca"=>"Africa/Casablanca",
    "africa/ceuta"=>"Africa/Ceuta",
    "africa/conakry"=>"Africa/Conakry",
    "africa/dakar"=>"Africa/Dakar",
    "africa/dar_es_salaam"=>"Africa/Dar_es_Salaam",
    "africa/djibouti"=>"Africa/Djibouti",
    "africa/douala"=>"Africa/Douala",
    "africa/el_aaiun"=>"Africa/El_Aaiun",
    "africa/freetown"=>"Africa/Freetown",
    "africa/gaborone"=>"Africa/Gaborone",
    "africa/harare"=>"Africa/Harare",
    "africa/johannesburg"=>"Africa/Johannesburg",
    "africa/kampala"=>"Africa/Kampala",
    "africa/khartoum"=>"Africa/Khartoum",
    "africa/kigali"=>"Africa/Kigali",
    "africa/kinshasa"=>"Africa/Kinshasa",
    "africa/lagos"=>"Africa/Lagos",
    "africa/libreville"=>"Africa/Libreville",
    "africa/lome"=>"Africa/Lome",
    "africa/luanda"=>"Africa/Luanda",
    "africa/lubumbashi"=>"Africa/Lubumbashi",
    "africa/lusaka"=>"Africa/Lusaka",
    "africa/malabo"=>"Africa/Malabo",
    "africa/maputo"=>"Africa/Maputo",
    "africa/maseru"=>"Africa/Maseru",
    "africa/mbabane"=>"Africa/Mbabane",
    "africa/mogadishu"=>"Africa/Mogadishu",
    "africa/monrovia"=>"Africa/Monrovia",
    "africa/nairobi"=>"Africa/Nairobi",
    "africa/ndjamena"=>"Africa/Ndjamena",
    "africa/niamey"=>"Africa/Niamey",
    "africa/nouakchott"=>"Africa/Nouakchott",
    "africa/ouagadougou"=>"Africa/Ouagadougou",
    "africa/porto-novo"=>"Africa/Porto-Novo",
    "africa/sao_tome"=>"Africa/Sao_Tome",
    "africa/timbuktu"=>"Africa/Timbuktu",
    "africa/tripoli"=>"Africa/Tripoli",
    "africa/tunis"=>"Africa/Tunis",
    "africa/windhoek"=>"Africa/Windhoek",
    "america/adak"=>"America/Adak",
    "america/anchorage"=>"America/Anchorage",
    "america/anguilla"=>"America/Anguilla",
    "america/antigua"=>"America/Antigua",
    "america/araguaina"=>"America/Araguaina",
    "america/aruba"=>"America/Aruba",
    "america/asuncion"=>"America/Asuncion",
    "america/atka"=>"America/Atka",
    "america/barbados"=>"America/Barbados",
    "america/belem"=>"America/Belem",
    "america/belize"=>"America/Belize",
    "america/boa_vista"=>"America/Boa_Vista",
    "america/bogota"=>"America/Bogota",
    "america/boise"=>"America/Boise",
    "america/buenos_aires"=>"America/Buenos_Aires",
    "america/cambridge_bay"=>"America/Cambridge_Bay",
    "america/cancun"=>"America/Cancun",
    "america/caracas"=>"America/Caracas",
    "america/catamarca"=>"America/Catamarca",
    "america/cayenne"=>"America/Cayenne",
    "america/cayman"=>"America/Cayman",
    "america/chicago"=>"America/Chicago",
    "america/chihuahua"=>"America/Chihuahua",
    "america/cordoba"=>"America/Cordoba",
    "america/costa_rica"=>"America/Costa_Rica",
    "america/cuiaba"=>"America/Cuiaba",
    "america/curacao"=>"America/Curacao",
    "america/dawson"=>"America/Dawson",
    "america/dawson_creek"=>"America/Dawson_Creek",
    "america/denver"=>"America/Denver",
    "america/detroit"=>"America/Detroit",
    "america/dominica"=>"America/Dominica",
    "america/edmonton"=>"America/Edmonton",
    "america/eirunepe"=>"America/Eirunepe",
    "america/el_salvador"=>"America/El_Salvador",
    "america/ensenada"=>"America/Ensenada",
    "america/fort_wayne"=>"America/Fort_Wayne",
    "america/fortaleza"=>"America/Fortaleza",
    "america/glace_bay"=>"America/Glace_Bay",
    "america/godthab"=>"America/Godthab",
    "america/goose_bay"=>"America/Goose_Bay",
    "america/grand_turk"=>"America/Grand_Turk",
    "america/grenada"=>"America/Grenada",
    "america/guadeloupe"=>"America/Guadeloupe",
    "america/guatemala"=>"America/Guatemala",
    "america/guayaquil"=>"America/Guayaquil",
    "america/guyana"=>"America/Guyana",
    "america/halifax"=>"America/Halifax",
    "america/havana"=>"America/Havana",
    "america/hermosillo"=>"America/Hermosillo",
    "america/indiana/indianapolis"=>"America/Indiana/Indianapolis",
    "america/indiana/knox"=>"America/Indiana/Knox",
    "america/indiana/marengo"=>"America/Indiana/Marengo",
    "america/indiana/vevay"=>"America/Indiana/Vevay",
    "america/indianapolis"=>"America/Indianapolis",
    "america/inuvik"=>"America/Inuvik",
    "america/iqaluit"=>"America/Iqaluit",
    "america/jamaica"=>"America/Jamaica",
    "america/jujuy"=>"America/Jujuy",
    "america/juneau"=>"America/Juneau",
    "america/kentucky/louisville"=>"America/Kentucky/Louisville",
    "america/kentucky/monticello"=>"America/Kentucky/Monticello",
    "america/knox_in"=>"America/Knox_IN",
    "america/la_paz"=>"America/La_Paz",
    "america/lima"=>"America/Lima",
    "america/los_angeles"=>"America/Los_Angeles",
    "america/louisville"=>"America/Louisville",
    "america/maceio"=>"America/Maceio",
    "america/managua"=>"America/Managua",
    "america/manaus"=>"America/Manaus",
    "america/martinique"=>"America/Martinique",
    "america/mazatlan"=>"America/Mazatlan",
    "america/mendoza"=>"America/Mendoza",
    "america/menominee"=>"America/Menominee",
    "america/merida"=>"America/Merida",
    "america/mexico_city"=>"America/Mexico_City",
    "america/miquelon"=>"America/Miquelon",
    "america/monterrey"=>"America/Monterrey",
    "america/montevideo"=>"America/Montevideo",
    "america/montreal"=>"America/Montreal",
    "america/montserrat"=>"America/Montserrat",
    "america/nassau"=>"America/Nassau",
    "america/new_york"=>"America/New_York",
    "america/nipigon"=>"America/Nipigon",
    "america/nome"=>"America/Nome",
    "america/noronha"=>"America/Noronha",
    "america/panama"=>"America/Panama",
    "america/pangnirtung"=>"America/Pangnirtung",
    "america/paramaribo"=>"America/Paramaribo",
    "america/phoenix"=>"America/Phoenix",
    "america/port_of_spain"=>"America/Port_of_Spain",
    "america/port-au-prince"=>"America/Port-au-Prince",
    "america/porto_acre"=>"America/Porto_Acre",
    "america/porto_velho"=>"America/Porto_Velho",
    "america/puerto_rico"=>"America/Puerto_Rico",
    "america/rainy_river"=>"America/Rainy_River",
    "america/rankin_inlet"=>"America/Rankin_Inlet",
    "america/recife"=>"America/Recife",
    "america/regina"=>"America/Regina",
    "america/rio_branco"=>"America/Rio_Branco",
    "america/rosario"=>"America/Rosario",
    "america/santiago"=>"America/Santiago",
    "america/santo_domingo"=>"America/Santo_Domingo",
    "america/sao_paulo"=>"America/Sao_Paulo",
    "america/scoresbysund"=>"America/Scoresbysund",
    "america/shiprock"=>"America/Shiprock",
    "america/st_johns"=>"America/St_Johns",
    "america/st_kitts"=>"America/St_Kitts",
    "america/st_lucia"=>"America/St_Lucia",
    "america/st_thomas"=>"America/St_Thomas",
    "america/st_vincent"=>"America/St_Vincent",
    "america/swift_current"=>"America/Swift_Current",
    "america/tegucigalpa"=>"America/Tegucigalpa",
    "america/thule"=>"America/Thule",
    "america/thunder_bay"=>"America/Thunder_Bay",
    "america/tijuana"=>"America/Tijuana",
    "america/tortola"=>"America/Tortola",
    "america/vancouver"=>"America/Vancouver",
    "america/virgin"=>"America/Virgin",
    "america/whitehorse"=>"America/Whitehorse",
    "america/winnipeg"=>"America/Winnipeg",
    "america/yakutat"=>"America/Yakutat",
    "america/yellowknife"=>"America/Yellowknife",
    "antarctica/casey"=>"Antarctica/Casey",
    "antarctica/davis"=>"Antarctica/Davis",
    "antarctica/dumontdurville"=>"Antarctica/DumontDUrville",
    "antarctica/mawson"=>"Antarctica/Mawson",
    "antarctica/mcmurdo"=>"Antarctica/McMurdo",
    "antarctica/palmer"=>"Antarctica/Palmer",
    "antarctica/south_pole"=>"Antarctica/South_Pole",
    "antarctica/syowa"=>"Antarctica/Syowa",
    "antarctica/vostok"=>"Antarctica/Vostok",
    "arctic/longyearbyen"=>"Arctic/Longyearbyen",
    "asia/aden"=>"Asia/Aden",
    "asia/almaty"=>"Asia/Almaty",
    "asia/amman"=>"Asia/Amman",
    "asia/anadyr"=>"Asia/Anadyr",
    "asia/aqtau"=>"Asia/Aqtau",
    "asia/aqtobe"=>"Asia/Aqtobe",
    "asia/ashgabat"=>"Asia/Ashgabat",
    "asia/ashkhabad"=>"Asia/Ashkhabad",
    "asia/baghdad"=>"Asia/Baghdad",
    "asia/bahrain"=>"Asia/Bahrain",
    "asia/baku"=>"Asia/Baku",
    "asia/bangkok"=>"Asia/Bangkok",
    "asia/beirut"=>"Asia/Beirut",
    "asia/bishkek"=>"Asia/Bishkek",
    "asia/brunei"=>"Asia/Brunei",
    "asia/calcutta"=>"Asia/Calcutta",
    "asia/chungking"=>"Asia/Chungking",
    "asia/colombo"=>"Asia/Colombo",
    "asia/dacca"=>"Asia/Dacca",
    "asia/damascus"=>"Asia/Damascus",
    "asia/dhaka"=>"Asia/Dhaka",
    "asia/dili"=>"Asia/Dili",
    "asia/dubai"=>"Asia/Dubai",
    "asia/dushanbe"=>"Asia/Dushanbe",
    "asia/gaza"=>"Asia/Gaza",
    "asia/harbin"=>"Asia/Harbin",
    "asia/hong_kong"=>"Asia/Hong_Kong",
    "asia/hovd"=>"Asia/Hovd",
    "asia/irkutsk"=>"Asia/Irkutsk",
    "asia/istanbul"=>"Asia/Istanbul",
    "asia/jakarta"=>"Asia/Jakarta",
    "asia/jayapura"=>"Asia/Jayapura",
    "asia/jerusalem"=>"Asia/Jerusalem",
    "asia/kabul"=>"Asia/Kabul",
    "asia/kamchatka"=>"Asia/Kamchatka",
    "asia/karachi"=>"Asia/Karachi",
    "asia/kashgar"=>"Asia/Kashgar",
    "asia/katmandu"=>"Asia/Katmandu",
    "asia/krasnoyarsk"=>"Asia/Krasnoyarsk",
    "asia/kuala_lumpur"=>"Asia/Kuala_Lumpur",
    "asia/kuching"=>"Asia/Kuching",
    "asia/kuwait"=>"Asia/Kuwait",
    "asia/macao"=>"Asia/Macao",
    "asia/magadan"=>"Asia/Magadan",
    "asia/manila"=>"Asia/Manila",
    "asia/muscat"=>"Asia/Muscat",
    "asia/nicosia"=>"Asia/Nicosia",
    "asia/novosibirsk"=>"Asia/Novosibirsk",
    "asia/omsk"=>"Asia/Omsk",
    "asia/phnom_penh"=>"Asia/Phnom_Penh",
    "asia/pontianak"=>"Asia/Pontianak",
    "asia/pyongyang"=>"Asia/Pyongyang",
    "asia/qatar"=>"Asia/Qatar",
    "asia/rangoon"=>"Asia/Rangoon",
    "asia/riyadh"=>"Asia/Riyadh",
    "asia/saigon"=>"Asia/Saigon",
    "asia/samarkand"=>"Asia/Samarkand",
    "asia/seoul"=>"Asia/Seoul",
    "asia/shanghai"=>"Asia/Shanghai",
    "asia/singapore"=>"Asia/Singapore",
    "asia/taipei"=>"Asia/Taipei",
    "asia/tashkent"=>"Asia/Tashkent",
    "asia/tbilisi"=>"Asia/Tbilisi",
    "asia/tehran"=>"Asia/Tehran",
    "asia/tel_aviv"=>"Asia/Tel_Aviv",
    "asia/thimbu"=>"Asia/Thimbu",
    "asia/thimphu"=>"Asia/Thimphu",
    "asia/tokyo"=>"Asia/Tokyo",
    "asia/ujung_pandang"=>"Asia/Ujung_Pandang",
    "asia/ulaanbaatar"=>"Asia/Ulaanbaatar",
    "asia/ulan_bator"=>"Asia/Ulan_Bator",
    "asia/urumqi"=>"Asia/Urumqi",
    "asia/vientiane"=>"Asia/Vientiane",
    "asia/vladivostok"=>"Asia/Vladivostok",
    "asia/yakutsk"=>"Asia/Yakutsk",
    "asia/yekaterinburg"=>"Asia/Yekaterinburg",
    "asia/yerevan"=>"Asia/Yerevan",
    "atlantic/azores"=>"Atlantic/Azores",
    "atlantic/bermuda"=>"Atlantic/Bermuda",
    "atlantic/canary"=>"Atlantic/Canary",
    "atlantic/cape_verde"=>"Atlantic/Cape_Verde",
    "atlantic/faeroe"=>"Atlantic/Faeroe",
    "atlantic/jan_mayen"=>"Atlantic/Jan_Mayen",
    "atlantic/madeira"=>"Atlantic/Madeira",
    "atlantic/reykjavik"=>"Atlantic/Reykjavik",
    "atlantic/south_georgia"=>"Atlantic/South_Georgia",
    "atlantic/st_helena"=>"Atlantic/St_Helena",
    "atlantic/stanley"=>"Atlantic/Stanley",
    "australia/act"=>"Australia/ACT",
    "australia/adelaide"=>"Australia/Adelaide",
    "australia/brisbane"=>"Australia/Brisbane",
    "australia/broken_hill"=>"Australia/Broken_Hill",
    "australia/canberra"=>"Australia/Canberra",
    "australia/darwin"=>"Australia/Darwin",
    "australia/hobart"=>"Australia/Hobart",
    "australia/lhi"=>"Australia/LHI",
    "australia/lindeman"=>"Australia/Lindeman",
    "australia/lord_howe"=>"Australia/Lord_Howe",
    "australia/melbourne"=>"Australia/Melbourne",
    "australia/north"=>"Australia/North",
    "australia/nsw"=>"Australia/NSW",
    "australia/perth"=>"Australia/Perth",
    "australia/queensland"=>"Australia/Queensland",
    "australia/south"=>"Australia/South",
    "australia/sydney"=>"Australia/Sydney",
    "australia/tasmania"=>"Australia/Tasmania",
    "australia/victoria"=>"Australia/Victoria",
    "australia/west"=>"Australia/West",
    "australia/yancowinna"=>"Australia/Yancowinna",
    "brazil/acre"=>"Brazil/Acre",
    "brazil/denoronha"=>"Brazil/DeNoronha",
    "brazil/east"=>"Brazil/East",
    "brazil/west"=>"Brazil/West",
    "canada/atlantic"=>"Canada/Atlantic",
    "canada/central"=>"Canada/Central",
    "canada/east-saskatchewan"=>"Canada/East-Saskatchewan",
    "canada/eastern"=>"Canada/Eastern",
    "canada/mountain"=>"Canada/Mountain",
    "canada/newfoundland"=>"Canada/Newfoundland",
    "canada/pacific"=>"Canada/Pacific",
    "canada/saskatchewan"=>"Canada/Saskatchewan",
    "canada/yukon"=>"Canada/Yukon",
    "cet"=>"CET",
    "chile/continental"=>"Chile/Continental",
    "chile/easterisland"=>"Chile/EasterIsland",
    "cst6cdt"=>"CST6CDT",
    "cuba"=>"Cuba",
    "eet"=>"EET",
    "egypt"=>"Egypt",
    "eire"=>"Eire",
    "est"=>"EST",
    "est5edt"=>"EST5EDT",
    "europe/amsterdam"=>"Europe/Amsterdam",
    "europe/andorra"=>"Europe/Andorra",
    "europe/athens"=>"Europe/Athens",
    "europe/belfast"=>"Europe/Belfast",
    "europe/berlin"=>"Europe/Berlin",
    "europe/bratislava"=>"Europe/Bratislava",
    "europe/brussels"=>"Europe/Brussels",
    "europe/bucharest"=>"Europe/Bucharest",
    "europe/budapest"=>"Europe/Budapest",
    "europe/chisinau"=>"Europe/Chisinau",
    "europe/copenhagen"=>"Europe/Copenhagen",
    "europe/dublin"=>"Europe/Dublin",
    "europe/gibraltar"=>"Europe/Gibraltar",
    "europe/helsinki"=>"Europe/Helsinki",
    "europe/kaliningrad"=>"Europe/Kaliningrad",
    "europe/kiev"=>"Europe/Kiev",
    "europe/luxembourg"=>"Europe/Luxembourg",
    "europe/madrid"=>"Europe/Madrid",
    "europe/malta"=>"Europe/Malta",
    "europe/minsk"=>"Europe/Minsk",
    "europe/monaco"=>"Europe/Monaco",
    "europe/nicosia"=>"Europe/Nicosia",
    "europe/oslo"=>"Europe/Oslo",
    "europe/paris"=>"Europe/Paris",
    "europe/prague"=>"Europe/Prague",
    "europe/riga"=>"Europe/Riga",
    "europe/samara"=>"Europe/Samara",
    "europe/simferopol"=>"Europe/Simferopol",
    "europe/sofia"=>"Europe/Sofia",
    "europe/stockholm"=>"Europe/Stockholm",
    "europe/tallinn"=>"Europe/Tallinn",
    "europe/tirane"=>"Europe/Tirane",
    "europe/tiraspol"=>"Europe/Tiraspol",
    "europe/uzhgorod"=>"Europe/Uzhgorod",
    "europe/vaduz"=>"Europe/Vaduz",
    "europe/vatican"=>"Europe/Vatican",
    "gb"=>"GB",
    "gb-eire"=>"GB-Eire",
    "gmt"=>"GMT",
    "gmt-0"=>"GMT-0",
    "gmt+0"=>"GMT+0",
    "gmt0"=>"GMT0",
    "greenwich"=>"Greenwich",
    "hongkong"=>"Hongkong",
    "hst"=>"HST",
    "iceland"=>"Iceland",
    "indian/antananarivo"=>"Indian/Antananarivo",
    "indian/chagos"=>"Indian/Chagos",
    "indian/christmas"=>"Indian/Christmas",
    "indian/cocos"=>"Indian/Cocos",
    "indian/comoro"=>"Indian/Comoro",
    "indian/kerguelen"=>"Indian/Kerguelen",
    "indian/mahe"=>"Indian/Mahe",
    "indian/maldives"=>"Indian/Maldives",
    "indian/mauritius"=>"Indian/Mauritius",
    "indian/mayotte"=>"Indian/Mayotte",
    "indian/reunion"=>"Indian/Reunion",
    "iran"=>"Iran",
    "israel"=>"Israel",
    "jamaica"=>"Jamaica",
    "japan"=>"Japan",
    "kwajalein"=>"Kwajalein",
    "libya"=>"Libya",
    "met"=>"MET",
    "mexico/bajanorte"=>"Mexico/BajaNorte",
    "mexico/bajasur"=>"Mexico/BajaSur",
    "mexico/general"=>"Mexico/General",
    "mst"=>"MST",
    "mst7mdt"=>"MST7MDT",
    "navajo"=>"Navajo",
    "nz"=>"NZ",
    "nz-chat"=>"NZ-CHAT",
    "pacific/apia"=>"Pacific/Apia",
    "pacific/auckland"=>"Pacific/Auckland",
    "pacific/chatham"=>"Pacific/Chatham",
    "pacific/easter"=>"Pacific/Easter",
    "pacific/efate"=>"Pacific/Efate",
    "pacific/enderbury"=>"Pacific/Enderbury",
    "pacific/fakaofo"=>"Pacific/Fakaofo",
    "pacific/fiji"=>"Pacific/Fiji",
    "pacific/funafuti"=>"Pacific/Funafuti",
    "pacific/galapagos"=>"Pacific/Galapagos",
    "pacific/gambier"=>"Pacific/Gambier",
    "pacific/guadalcanal"=>"Pacific/Guadalcanal",
    "pacific/guam"=>"Pacific/Guam",
    "pacific/honolulu"=>"Pacific/Honolulu",
    "pacific/johnston"=>"Pacific/Johnston",
    "pacific/kiritimati"=>"Pacific/Kiritimati",
    "pacific/kosrae"=>"Pacific/Kosrae",
    "pacific/kwajalein"=>"Pacific/Kwajalein",
    "pacific/majuro"=>"Pacific/Majuro",
    "pacific/marquesas"=>"Pacific/Marquesas",
    "pacific/midway"=>"Pacific/Midway",
    "pacific/nauru"=>"Pacific/Nauru",
    "pacific/niue"=>"Pacific/Niue",
    "pacific/norfolk"=>"Pacific/Norfolk",
    "pacific/noumea"=>"Pacific/Noumea",
    "pacific/pago_pago"=>"Pacific/Pago_Pago",
    "pacific/palau"=>"Pacific/Palau",
    "pacific/pitcairn"=>"Pacific/Pitcairn",
    "pacific/ponape"=>"Pacific/Ponape",
    "pacific/port_moresby"=>"Pacific/Port_Moresby",
    "pacific/rarotonga"=>"Pacific/Rarotonga",
    "pacific/saipan"=>"Pacific/Saipan",
    "pacific/samoa"=>"Pacific/Samoa",
    "pacific/tahiti"=>"Pacific/Tahiti",
    "pacific/tarawa"=>"Pacific/Tarawa",
    "pacific/tongatapu"=>"Pacific/Tongatapu",
    "pacific/truk"=>"Pacific/Truk",
    "pacific/wake"=>"Pacific/Wake",
    "pacific/wallis"=>"Pacific/Wallis",
    "pacific/yap"=>"Pacific/Yap",
    "poland"=>"Poland",
    "portugal"=>"Portugal",
    "prc"=>"PRC",
    "pst8pdt"=>"PST8PDT",
    "roc"=>"ROC",
    "rok"=>"ROK",
    "singapore"=>"Singapore",
    "turkey"=>"Turkey",
    "uct"=>"UCT",
    "universal"=>"Universal",
    "us/alaska"=>"US/Alaska",
    "us/aleutian"=>"US/Aleutian",
    "us/arizona"=>"US/Arizona",
    "us/central"=>"US/Central",
    "us/east-indiana"=>"US/East-Indiana",
    "us/eastern"=>"US/Eastern",
    "us/hawaii"=>"US/Hawaii",
    "us/indiana-starke"=>"US/Indiana-Starke",
    "us/michigan"=>"US/Michigan",
    "us/mountain"=>"US/Mountain",
    "us/pacific"=>"US/Pacific",
    "us/samoa"=>"US/Samoa",
    "utc"=>"UTC",
    "w-su"=>"W-SU",
    "wet"=>"WET",
    "zulu"=>"Zulu"
};

static PLACE_TIMEZONES: phf::Map<&'static str, &'static str> = phf_map! {
    "International Date Line West" => "Etc/GMT+12",
    "Midway Island"                => "Pacific/Midway",
    "American Samoa"               => "Pacific/Pago_Pago",
    "Hawaii"                       => "Pacific/Honolulu",
    "Alaska"                       => "America/Juneau",
    "Pacific Time (US & Canada)"   => "America/Los_Angeles",
    "Tijuana"                      => "America/Tijuana",
    "Mountain Time (US & Canada)"  => "America/Denver",
    "Arizona"                      => "America/Phoenix",
    "Chihuahua"                    => "America/Chihuahua",
    "Mazatlan"                     => "America/Mazatlan",
    "Central Time (US & Canada)"   => "America/Chicago",
    "Saskatchewan"                 => "America/Regina",
    "Guadalajara"                  => "America/Mexico_City",
    "Mexico City"                  => "America/Mexico_City",
    "Monterrey"                    => "America/Monterrey",
    "Central America"              => "America/Guatemala",
    "Eastern Time (US & Canada)"   => "America/New_York",
    "Indiana (East)"               => "America/Indiana/Indianapolis",
    "Bogota"                       => "America/Bogota",
    "Lima"                         => "America/Lima",
    "Quito"                        => "America/Lima",
    "Atlantic Time (Canada)"       => "America/Halifax",
    "Caracas"                      => "America/Caracas",
    "La Paz"                       => "America/La_Paz",
    "Santiago"                     => "America/Santiago",
    "Newfoundland"                 => "America/St_Johns",
    "Brasilia"                     => "America/Sao_Paulo",
    "Buenos Aires"                 => "America/Argentina/Buenos_Aires",
    "Montevideo"                   => "America/Montevideo",
    "Georgetown"                   => "America/Guyana",
    "Puerto Rico"                  => "America/Puerto_Rico",
    "Greenland"                    => "America/Godthab",
    "Mid-Atlantic"                 => "Atlantic/South_Georgia",
    "Azores"                       => "Atlantic/Azores",
    "Cape Verde Is."               => "Atlantic/Cape_Verde",
    "Dublin"                       => "Europe/Dublin",
    "Edinburgh"                    => "Europe/London",
    "Lisbon"                       => "Europe/Lisbon",
    "London"                       => "Europe/London",
    "Casablanca"                   => "Africa/Casablanca",
    "Monrovia"                     => "Africa/Monrovia",
    "UTC"                          => "Etc/UTC",
    "Belgrade"                     => "Europe/Belgrade",
    "Bratislava"                   => "Europe/Bratislava",
    "Budapest"                     => "Europe/Budapest",
    "Ljubljana"                    => "Europe/Ljubljana",
    "Prague"                       => "Europe/Prague",
    "Sarajevo"                     => "Europe/Sarajevo",
    "Skopje"                       => "Europe/Skopje",
    "Warsaw"                       => "Europe/Warsaw",
    "Zagreb"                       => "Europe/Zagreb",
    "Brussels"                     => "Europe/Brussels",
    "Copenhagen"                   => "Europe/Copenhagen",
    "Madrid"                       => "Europe/Madrid",
    "Paris"                        => "Europe/Paris",
    "Amsterdam"                    => "Europe/Amsterdam",
    "Berlin"                       => "Europe/Berlin",
    "Bern"                         => "Europe/Zurich",
    "Zurich"                       => "Europe/Zurich",
    "Rome"                         => "Europe/Rome",
    "Stockholm"                    => "Europe/Stockholm",
    "Vienna"                       => "Europe/Vienna",
    "West Central Africa"          => "Africa/Algiers",
    "Bucharest"                    => "Europe/Bucharest",
    "Cairo"                        => "Africa/Cairo",
    "Helsinki"                     => "Europe/Helsinki",
    "Kyiv"                         => "Europe/Kiev",
    "Riga"                         => "Europe/Riga",
    "Sofia"                        => "Europe/Sofia",
    "Tallinn"                      => "Europe/Tallinn",
    "Vilnius"                      => "Europe/Vilnius",
    "Athens"                       => "Europe/Athens",
    "Istanbul"                     => "Europe/Istanbul",
    "Minsk"                        => "Europe/Minsk",
    "Jerusalem"                    => "Asia/Jerusalem",
    "Harare"                       => "Africa/Harare",
    "Pretoria"                     => "Africa/Johannesburg",
    "Kaliningrad"                  => "Europe/Kaliningrad",
    "Moscow"                       => "Europe/Moscow",
    "St. Petersburg"               => "Europe/Moscow",
    "Volgograd"                    => "Europe/Volgograd",
    "Samara"                       => "Europe/Samara",
    "Kuwait"                       => "Asia/Kuwait",
    "Riyadh"                       => "Asia/Riyadh",
    "Nairobi"                      => "Africa/Nairobi",
    "Baghdad"                      => "Asia/Baghdad",
    "Tehran"                       => "Asia/Tehran",
    "Abu Dhabi"                    => "Asia/Muscat",
    "Muscat"                       => "Asia/Muscat",
    "Baku"                         => "Asia/Baku",
    "Tbilisi"                      => "Asia/Tbilisi",
    "Yerevan"                      => "Asia/Yerevan",
    "Kabul"                        => "Asia/Kabul",
    "Ekaterinburg"                 => "Asia/Yekaterinburg",
    "Islamabad"                    => "Asia/Karachi",
    "Karachi"                      => "Asia/Karachi",
    "Tashkent"                     => "Asia/Tashkent",
    "Chennai"                      => "Asia/Kolkata",
    "Kolkata"                      => "Asia/Kolkata",
    "Mumbai"                       => "Asia/Kolkata",
    "New Delhi"                    => "Asia/Kolkata",
    "Kathmandu"                    => "Asia/Kathmandu",
    "Astana"                       => "Asia/Dhaka",
    "Dhaka"                        => "Asia/Dhaka",
    "Sri Jayawardenepura"          => "Asia/Colombo",
    "Almaty"                       => "Asia/Almaty",
    "Novosibirsk"                  => "Asia/Novosibirsk",
    "Rangoon"                      => "Asia/Rangoon",
    "Bangkok"                      => "Asia/Bangkok",
    "Hanoi"                        => "Asia/Bangkok",
    "Jakarta"                      => "Asia/Jakarta",
    "Krasnoyarsk"                  => "Asia/Krasnoyarsk",
    "Beijing"                      => "Asia/Shanghai",
    "Chongqing"                    => "Asia/Chongqing",
    "Hong Kong"                    => "Asia/Hong_Kong",
    "Urumqi"                       => "Asia/Urumqi",
    "Kuala Lumpur"                 => "Asia/Kuala_Lumpur",
    "Singapore"                    => "Asia/Singapore",
    "Taipei"                       => "Asia/Taipei",
    "Perth"                        => "Australia/Perth",
    "Irkutsk"                      => "Asia/Irkutsk",
    "Ulaanbaatar"                  => "Asia/Ulaanbaatar",
    "Seoul"                        => "Asia/Seoul",
    "Osaka"                        => "Asia/Tokyo",
    "Sapporo"                      => "Asia/Tokyo",
    "Tokyo"                        => "Asia/Tokyo",
    "Yakutsk"                      => "Asia/Yakutsk",
    "Darwin"                       => "Australia/Darwin",
    "Adelaide"                     => "Australia/Adelaide",
    "Canberra"                     => "Australia/Melbourne",
    "Melbourne"                    => "Australia/Melbourne",
    "Sydney"                       => "Australia/Sydney",
    "Brisbane"                     => "Australia/Brisbane",
    "Hobart"                       => "Australia/Hobart",
    "Vladivostok"                  => "Asia/Vladivostok",
    "Guam"                         => "Pacific/Guam",
    "Port Moresby"                 => "Pacific/Port_Moresby",
    "Magadan"                      => "Asia/Magadan",
    "Srednekolymsk"                => "Asia/Srednekolymsk",
    "Solomon Is."                  => "Pacific/Guadalcanal",
    "New Caledonia"                => "Pacific/Noumea",
    "Fiji"                         => "Pacific/Fiji",
    "Kamchatka"                    => "Asia/Kamchatka",
    "Marshall Is."                 => "Pacific/Majuro",
    "Auckland"                     => "Pacific/Auckland",
    "Wellington"                   => "Pacific/Auckland",
    "Nuku'alofa"                   => "Pacific/Tongatapu",
    "Tokelau Is."                  => "Pacific/Fakaofo",
    "Chatham Is."                  => "Pacific/Chatham",
    "Samoa"                        => "Pacific/Apia"
  };

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unit_timezone() {
        assert_eq!(
            liquid_core::call_filter!(TimeZone, "").unwrap(),
            liquid_core::value!("")
        );
        assert_eq!(
            liquid_core::call_filter!(TimeZone, "foo_bar_baz").unwrap(),
            liquid_core::value!("foo_bar_baz")
        );

        assert_eq!(
            liquid_core::call_filter!(TimeZone, "03/12/2024", "UTC").unwrap(),
            liquid_core::value!("Foo::Bar::Baz")
        );
    }

}
